### ISSUE TITLE
Accessible historical sensitive information

### ISSUE THREAD

**Issue by karmiphuc** [MortgageClub/HappyLunch#35]
Please make sure you guys have invalidated those sensitive information that can be retrieved from git history.

- File: https://github.com/MortgageClub/HappyLunch/commits/master/app/controllers/lunch_controller.rb
- Commit: https://github.com/MortgageClub/HappyLunch/commit/42405e46bfa042e36c1d5f573473c1a19deafdb0

**Comment by vumanhcuongit** [comment]
Good catch! @karmiphuc :+1: 
We've regenerated these secret tokens
